version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres-db
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      NODE_ENV: development
      PORT: 5000
      DB_NAME: test
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DIALECT: postgres
      JWT_SECRET: ';ylsshdjcflydktrjz8768756gcg'
  postgres-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
